config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  root to: redirect('/dashboard')

  namespace :dashboard do
    root to: 'dashboard#index' # Preservation System Status Overview page

    resources :objects, only: [:show], param: :druid do # show -> Object show page
      member do
        post 'checksum_validation'
        post 'replication_audit'
      end
    end

    resources :moab_records, only: [:index] do # index -> Files in moabs on local storage page
      collection do
        get 'with_errors' # MoabRecords in error statuses list page
        get 'stuck' # Stuck MoabRecords list page
      end
    end

    resources :zipped_moab_versions, only: [:index] do # Replication of zip part files to cloud endpoints page
      collection do
        get 'with_errors' # ZipppedMoabVersion in failed status list page
        get 'stuck' # Stuck ZippedMoabVersions list page
        get 'incomplete' # Incomplete ZippedMoabVersions list page
      end
    end

    resources :search, param: :druid, only: [:create]
  end

  scope 'v1' do
    resources :catalog, param: :druid, only: %i[create update]

    resources :objects, only: %i[show] do
      member do
        get 'ok'
        get 'checksum'
        get 'validate_moab'
        get 'file', format: false # no need to add extension to url
        post 'content_diff'
      end
    end
  end
end

app/controllers/dashboard/base_controller.rb
# frozen_string_literal: true

module Dashboard
  # Base controller for dashboard controllers
  class BaseController < ApplicationController
    layout 'dashboard'
  end
end

app/controllers/dashboard/dashboard_controller.rb
# frozen_string_literal: true

module Dashboard
  # Controller for the dashboard
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/dashboard/moab_records_controller.rb
# frozen_string_literal: true

module Dashboard
  # Controller for listing MoabRecords in the dashboard
  class MoabRecordsController < BaseController
    def index
      @results, @total_result = MoabRecord.moab_records_by_moab_storage_root
    end

    def with_errors
      @moab_records = MoabRecord.with_errors.eager_load(:preserved_object).order(:updated_at).page(params[:page])
    end

    def stuck
      @moab_records = MoabRecord.stuck.eager_load(:preserved_object).order(:updated_at).page(params[:page])
    end
  end
end

app/controllers/dashboard/objects_controller.rb
# frozen_string_literal: true

module Dashboard
  # Minimal controller for displaying a PreservedObject
  class ObjectsController < BaseController
    before_action :set_preserved_object

    def show; end

    def checksum_validation
      @preserved_object.moab_record.validate_checksums!

      flash[:notice] = "Checksum validation job started for #{@druid}."
      redirect_to dashboard_object_path(@druid)
    end

    def replication_audit
      @preserved_object.audit_moab_version_replication!

      flash[:notice] = "Replication audit job started for #{@druid}."
      redirect_to dashboard_object_path(@druid)
    end

    private

    def set_preserved_object
      @druid = params[:druid].delete_prefix('druid:')
      @preserved_object = PreservedObject.find_by(druid: @druid)
    end
  end
end

app/controllers/dashboard/search_controller.rb
# frozen_string_literal: true

module Dashboard
  # Minimal search controller for dashboard druid search
  class SearchController < BaseController
    def create
      redirect_to dashboard_object_path(druid:)
    end

    private

    def druid
      params[:druid]
    end
  end
end

app/controllers/dashboard/zipped_moab_versions_controller.rb
# frozen_string_literal: true

module Dashboard
  # Controller for listing ZippedMoabVersions in the dashboard
  class ZippedMoabVersionsController < BaseController
    def index
      @results, @total_result = ZippedMoabVersion.zipped_moab_versions_by_zip_endpoint
    end

    def with_errors
      @zipped_moab_versions = ZippedMoabVersion.with_errors.eager_load(:preserved_object, :zip_endpoint).order(:status_updated_at).page(params[:page])
    end

    def stuck
      @zipped_moab_versions = ZippedMoabVersion.stuck.eager_load(:preserved_object, :zip_endpoint).order(:status_updated_at).page(params[:page])
    end

    def incomplete
      @zipped_moab_versions = ZippedMoabVersion.incomplete.eager_load(:preserved_object, :zip_endpoint).order(:status_updated_at).page(params[:page])
    end
  end
end

app/views/dashboard/dashboard/index.html.erb
<div class="container mt-4">
  <h1>Preservation System Status Overview</h1>

  <h2 class="mt-5">Object Status Errors</h2>
  <table class="table" id="status-errors-table">
    <thead>
      <tr>
        <th scope="col">Record type</th>
        <th scope="col">With errors</th>
        <th scope="col">Stuck</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">MoabRecords</th>
        <td><%= link_to number_with_delimiter(MoabRecord.with_errors.count), with_errors_dashboard_moab_records_path %></td>
        <td><%= link_to number_with_delimiter(MoabRecord.stuck.count), stuck_dashboard_moab_records_path %></td>
      </tr>
      <tr>
        <th scope="row">ZippedMoabVersions</th>
        <td><%= link_to number_with_delimiter(ZippedMoabVersion.with_errors.count), with_errors_dashboard_zipped_moab_versions_path %></td>
        <td><%= link_to number_with_delimiter(ZippedMoabVersion.stuck.count), stuck_dashboard_zipped_moab_versions_path %></td>
      </tr>
    </tbody>
  </table>

  <%= render CardComponent.new do %>
    <p class="fw-semibold">Any errors shown above require investigation.</p>
    <p class="mb-1"><span class="fw-medium">Stuck for MoabRecords:</span> status of <italic>validity_unknown</italic> for more than a week</p>
    <p class="mb-1"><span class="fw-medium">Stuck for ZippedMoabVersions:</span> status of <italic>created</italic> or <italic>incomplete</italic> for more than a week</p>
    <p>Each of the stuck statuses should be transient; if they persist, that indicates a problem.</p>
  <% end %>

  <hr class="my-5">

  <h2>System Level Warnings</h2>

  <table class="table" id="system-warnings-table">
    <thead>
      <tr>
        <th scope="col">Warning</th>
        <th scope="col">Count</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">MoabRecord with validity_unknown status</th>
        <td><%= number_with_delimiter(MoabRecord.validity_unknown_count) %></td>
      </tr>
      <tr>
        <th scope="row">ZippedMoabVersions with created status</th>
        <td><%= number_with_delimiter(ZippedMoabVersion.created_count) %></td>
      </tr>
      <tr>
        <th scope="row">ZippedMoabVersions with incomplete status</th>
        <td><%= link_to number_with_delimiter(ZippedMoabVersion.incomplete_count), incomplete_dashboard_zipped_moab_versions_path %></td>
      </tr>
      <tr>
        <th scope="row">Missing ZippedMoabVersions</th>
        <td><%= number_with_delimiter(ZippedMoabVersion.missing_count) %></td>
      </tr>
      <tr>
        <th scope="row">Expired MoabRecord checksum validations + 7 day grace</th>
        <td><%= number_with_delimiter(MoabRecord.expired_checksum_validation_with_grace_count) %></td>
      </tr>
      <tr>
        <th scope="row">Expired PreservedObject replication audits + 7 day grace</th>
        <td><%= number_with_delimiter(PreservedObject.expired_archive_audit_with_grace_count) %></td>
      </tr>
    </tbody>
  </table>

  <%= render CardComponent.new do %>
    <p class="fw-semibold">Large counts for any of the above may indicate system level issues that need investigation.</p>
    <p>In normal operation, a small number of objects in these states is expected.</p>
    <%= link_to 'Sidekiq Dashboard', sidekiq_web_path, class: 'card-link' %>
  <% end %>
</div>