config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  root to: redirect('/dashboard')

  namespace :dashboard do
    root to: 'dashboard#index' # Preservation System Status Overview page

    resources :objects, only: [:show], param: :druid do # show -> Object show page
      member do
        post 'checksum_validation'
        post 'replication_audit'
      end
    end

    resources :moab_records, only: [:index] do # index -> Files in moabs on local storage page
      collection do
        get 'with_errors' # MoabRecords in error statuses list page
        get 'stuck' # Stuck MoabRecords list page
      end
    end

    resources :zipped_moab_versions, only: [:index] do # Replication of zip part files to cloud endpoints page
      collection do
        get 'with_errors' # ZipppedMoabVersion in failed status list page
        get 'stuck' # Stuck ZippedMoabVersions list page
        get 'incomplete' # Incomplete ZippedMoabVersions list page
      end
    end

    resources :search, param: :druid, only: [:create]
  end

  scope 'v1' do
    resources :catalog, param: :druid, only: %i[create update]

    resources :objects, only: %i[show] do
      member do
        get 'ok'
        get 'checksum'
        get 'validate_moab'
        get 'file', format: false # no need to add extension to url
        post 'content_diff'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>SUL - Preservation Catalog</title>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<% content_for :content do %>
  <%# Dashboard Navbar %>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand d-flex align-items-center" href="#">
        <i class="bi bi-safe text-success fw-bold fs-2 me-2"></i>
        PresCat Dashboard
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Overview', dashboard_root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Files in moabs on local storage (MoabRecords)
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to 'Overview', dashboard_moab_records_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'With errors', with_errors_dashboard_moab_records_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Stuck', stuck_dashboard_moab_records_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Replication of zip parts to cloud storage (ZippedMoabVersions)
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to 'Overview', dashboard_zipped_moab_versions_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'With errors', with_errors_dashboard_zipped_moab_versions_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Stuck', stuck_dashboard_zipped_moab_versions_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Incomplete', incomplete_dashboard_zipped_moab_versions_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
        <%# Turbo doesn't play well with Shib, so disabling for this form. %>
        <%= form_with url: dashboard_search_index_path, method: :post, class: 'd-flex', role: 'search', data: { turbo: false } do %>
          <input class="form-control me-2" type="search" name="druid" placeholder="Search by druid" aria-label="Search by druid" autocomplete="off">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container my-2">
    <%= render AlertComponent.new %>
    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

  <%= yield %>
<% end %>
<%= render template: 'layouts/application' %>